### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by harivyasi** [Chemotion/ELNmap#2]
@blutzATkit Hi! I was thinking of adding the MIT Licence to this repository and releasing the code to public domain. Any objections?

**Comment by blutzATkit** [comment]
@harivyasi Hi! Go for it, no objections on my side :)

**Comment by harivyasi** [comment]
Thanks.
I will remove non-redistributable files from the main branch and then fix this issue by adding a LICENCE file

**Comment by harivyasi** [comment]
@blutzATkit Done and released to the wild. Thanks for the initial codebase. It was really helpful.
